"""Integral homology checks for the genus-two lift of six-strand braids.

The double cover of a disk branched at six points has genus two and two
boundary components. After capping them, the five standard half twists lift
to Dehn twists along a five-chain. This module computes only the induced
action on H_1 of the *closed* genus-two surface. Identity here alone does not
prove identity in its mapping class group. Together with an independently
verified identity action in Mod(S^2, 6 points), however, it distinguishes the
identity from the hyperelliptic involution, which acts as -I on H_1. Neither
certificate by itself establishes a section of a Lefschetz fibration.
"""

from itertools import combinations
from math import gcd


# Coordinates are (a1, a2, b1, b2), with a_i . b_j = delta_ij.
# Adjacent chain intersections have absolute value one; other pairs vanish.
CHAIN_CLASSES = (
    (1, 0, 0, 0),
    (0, 0, 1, 0),
    (1, 1, 0, 0),
    (0, 0, 0, 1),
    (0, 1, 0, 0),
)
IDENTITY = tuple(tuple(int(i == j) for j in range(4)) for i in range(4))


def _multiply(left, right):
    return tuple(tuple(sum(left[i][k] * right[k][j] for k in range(4))
                       for j in range(4)) for i in range(4))


def _twist(vector, sign):
    # T_v(x) = x + (x . v)v, so T_v = I + v(Jv)^T.
    jv = (vector[2], vector[3], -vector[0], -vector[1])
    return tuple(tuple(IDENTITY[i][j] + sign * vector[i] * jv[j]
                       for j in range(4)) for i in range(4))


def homology_action(word):
    """Return the Sp(4,Z) matrix of a signed six-strand braid word.

    Braid letters compose from left to right by matrix multiplication, as in
    the package's exact Artin action convention. A negative letter uses the
    inverse transvection. This forgets all Torelli information.
    """
    result = IDENTITY
    for letter in word:
        if type(letter) is not int or not 1 <= abs(letter) <= 5:
            raise ValueError('six-strand braid letters must be signed 1..5')
        result = _multiply(result, _twist(CHAIN_CLASSES[abs(letter) - 1],
                                          1 if letter > 0 else -1))
    return result


def half_twist_class(conjugator, first):
    """Homology class of the vanishing cycle for g sigma_first g^-1.

    The sign of this vector has no geometric significance. Full twists about
    three branch points lift to separating curves and have zero H_1 class;
    this function is only for half twists.
    """
    if type(first) is not int or not 1 <= first <= 5:
        raise ValueError('first must be a half-twist generator 1..5')
    matrix = homology_action(conjugator)
    vector = CHAIN_CLASSES[first - 1]
    return tuple(sum(matrix[i][j] * vector[j] for j in range(4))
                 for i in range(4))


def braid_permutation(word):
    """Return the original labels at the six bottom positions of a braid."""
    labels = list(range(1, 7))
    for letter in word:
        if type(letter) is not int or not 1 <= abs(letter) <= 5:
            raise ValueError('six-strand braid letters must be signed 1..5')
        i = abs(letter) - 1
        labels[i], labels[i + 1] = labels[i + 1], labels[i]
    return tuple(labels)


def branch_point_orbits(factor_words):
    """Find branch-label orbits generated by the supplied factor braids.

    A singleton orbit is a necessary condition for a section coming directly
    from one fixed ramification point. Non-singleton orbits can instead yield
    multisections. This permutation test does not find arbitrary sections.
    """
    parent = list(range(7))

    def find(i):
        while parent[i] != i:
            parent[i] = parent[parent[i]]
            i = parent[i]
        return i

    for word in factor_words:
        for position, label in enumerate(braid_permutation(word), 1):
            parent[find(position)] = find(label)
    groups = {}
    for label in range(1, 7):
        groups.setdefault(find(label), []).append(label)
    return tuple(sorted((tuple(labels) for labels in groups.values()),
                        key=lambda orbit: orbit[0]))


def _determinant(matrix):
    if len(matrix) == 1:
        return matrix[0][0]
    return sum((1 if j % 2 == 0 else -1) * entry *
               _determinant(tuple(row[:j] + row[j + 1:]
                                  for row in matrix[1:]))
               for j, entry in enumerate(matrix[0]))


def homology_quotient(vectors):
    """Describe Z^4 modulo the lattice spanned by vanishing-cycle classes.

    Returns the lattice rank, free quotient rank, and nontrivial finite cyclic
    factors. Determinantal divisors give the Smith invariants without a
    third-party algebra dependency. This is the abelianization of the
    vanishing-cycle quotient of the fiber group. Without a section, the last
    handle can impose an additional relation, so this is not automatically
    H_1 of the total space (nor a calculation of its pi_1).
    """
    vectors = tuple(tuple(vector) for vector in vectors)
    if any(len(vector) != 4 or any(type(value) is not int for value in vector)
           for vector in vectors):
        raise ValueError('each class must have four integer coordinates')
    divisors = [1]
    rank = 0
    for size in range(1, min(4, len(vectors)) + 1):
        divisor = 0
        for rows in combinations(range(4), size):
            for columns in combinations(range(len(vectors)), size):
                minor = tuple(tuple(vectors[column][row] for column in columns)
                              for row in rows)
                divisor = gcd(divisor, _determinant(minor))
        if not divisor:
            break
        divisors.append(divisor)
        rank = size
    invariants = tuple(divisors[i] // divisors[i - 1]
                       for i in range(1, rank + 1))
    return {'lattice_rank': rank, 'free_rank': 4 - rank,
            'torsion': tuple(value for value in invariants if value > 1)}
