/* A browser document editor, not a second geometry implementation. */
"use strict";
const $ = id => document.getElementById(id);
const clone = value => JSON.parse(JSON.stringify(value));
const ns = "http://www.w3.org/2000/svg";
let recipe, examples, token, preview, valid = false, revision = 0, zoom = 1;
let selectedCurve = null, selectedLabel = null, selectedStep = 0;
let tool = "select", start = null, visits = [], undo = [], redo = [], saved = "";
let renderTimer, drag = null;

function svgElement(name, attrs) {
  const element = document.createElementNS(ns, name);
  for (const [key, value] of Object.entries(attrs)) element.setAttribute(key, value);
  return element;
}
function showError(message) {
  $("error").textContent = message + " The preview is the last valid drawing; exports are disabled.";
  $("error").hidden = false;
  $("drawing").classList.add("stale");
  valid = false;
  $("export").disabled = true;
  $("status").textContent = "Draft needs attention. You can still save its JSON.";
}
async function api(path, body, raw = false) {
  const response = await fetch(path, {method: "POST", headers: {
    "Content-Type": "application/json", "X-Surface-Token": token
  }, body: raw ? body : JSON.stringify(body)});
  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.error || "The local renderer rejected this request.");
  }
  return response;
}
function dirty() { return recipe && JSON.stringify(recipe) !== saved; }
function saveStateLabel() { $("saved-state").textContent = dirty() ? "Unsaved" : "Saved"; }
function commit(next) {
  if (JSON.stringify(next) === JSON.stringify(recipe)) return;
  undo.push(clone(recipe));
  if (undo.length > 100) undo.shift();
  redo = [];
  recipe = next;
  sync();
  scheduleRender();
}
function history(backward) {
  const source = backward ? undo : redo, target = backward ? redo : undo;
  if (!source.length) return;
  target.push(clone(recipe));
  recipe = source.pop();
  setTool("select");
  sync(); scheduleRender();
}
function scheduleRender() {
  revision++;
  valid = false;
  $("export").disabled = true;
  $("status").textContent = "Checking geometry...";
  $("drawing").classList.add("stale");
  clearTimeout(renderTimer);
  renderTimer = setTimeout(render, 100);
}
async function render() {
  const current = revision;
  try {
    const result = await (await api("/api/render", recipe)).json();
    if (current !== revision) return; // An old response must never replace a newer edit.
    preview = result;
    recipe = result.document;
    // The only SVG accepted here is generated by the local library. Uploaded
    // SVG/HTML is never accepted or inserted into the document.
    const parsed = new DOMParser().parseFromString(result.svg, "image/svg+xml");
    if (parsed.querySelector("parsererror")) throw new Error("Renderer returned invalid SVG");
    $("drawing").replaceChildren(document.importNode(parsed.documentElement, true));
    $("drawing").classList.remove("stale");
    $("error").hidden = true;
    valid = true;
    $("export").disabled = false;
    $("status").textContent = recipe.kind === "braid" ? "Word drawn exactly as supplied. No equality check." :
      recipe.allow_intersections ? "Overlay drawn. Pairwise intersections are not certified." : "Geometry accepted by the library.";
    decorate(); applyZoom(); syncLists(); saveStateLabel();
    $("recipe").textContent = JSON.stringify(recipe, null, 2);
  } catch (error) { if (current === revision) showError(error.message); }
}
function number(id) {
  if (!$(id).value.trim() || !Number.isFinite(Number($(id).value))) throw new Error("Enter a finite number for " + id);
  return Number($(id).value);
}
function integers(text) {
  if (!text.trim()) return [];
  const parts = text.trim().split(/[\s,]+/);
  if (parts.some(p => !/^[+-]?\d+$/.test(p) || !Number.isSafeInteger(Number(p))))
    throw new Error("Use whole-number indices separated by spaces or commas.");
  return parts.map(Number);
}
function change(id, edit) {
  $(id).addEventListener("change", () => {
    try { const next = clone(recipe); edit(next); commit(next); }
    catch (error) { inputError(error.message); }
  });
}
function inputError(message) {
  // Invalid form text has not changed the recipe. Restore the last committed
  // value so a later successful render cannot silently conceal a rejected edit.
  sync();
  $("error").textContent = message + " That edit was not applied.";
  $("error").hidden = false;
}
function unique(prefix, records) {
  let i = 1;
  while (records.some(r => r.id === prefix+i)) i++;
  return prefix+i;
}
function itemButton(text, selected, action, color) {
  const button = document.createElement("button");
  button.type = "button";
  button.classList.toggle("selected", selected);
  if (color) { const swatch = document.createElement("span"); swatch.className = "swatch"; swatch.style.backgroundColor = color; button.append(swatch); }
  button.append(document.createTextNode(text));
  button.addEventListener("click", action);
  return button;
}
function syncLists() {
  const planar = recipe.kind === "planar";
  if (planar) {
    $("curve-count").textContent = `${recipe.curves.length} / 16`;
    $("curve-list").replaceChildren(...recipe.curves.map(c => itemButton(
      `${c.id} · ${c.kind === "arc" ? c.start+" → "+c.end : "loop"}`,
      c.id === selectedCurve, () => { selectedCurve = c.id; selectedLabel = null; syncLists(); decorate(); }, c.color)));
    const curve = recipe.curves.find(c => c.id === selectedCurve);
    $("curve-editor").hidden = !curve;
    if (curve) {
      $("curve-id").value = curve.id; $("curve-color").value = color6(curve.color);
      $("curve-cuts").value = curve.cuts.join(", ");
      $("arc-fields").hidden = curve.kind !== "arc"; $("loop-fields").hidden = curve.kind !== "loop";
      if (curve.kind === "arc") {
        $("curve-start").value = curve.start; $("curve-end").value = curve.end;
        $("curve-start").max = $("curve-end").max = recipe.surface.objects.length+1;
        $("curve-direction").value = curve.direction; $("start-side").value = curve.start_side || "";
        $("end-side").value = curve.end_side || "";
      } else $("loop-up").checked = curve.start_up;
    }
  } else {
    selectedStep = Math.max(0, Math.min(selectedStep, recipe.braid.word.length-1));
    $("crossing-list").replaceChildren(...recipe.braid.word.map((g, i) => itemButton(
      `${i+1}. ${g > 0 ? "+" : ""}${g}`, i === selectedStep, () => { selectedStep = i; syncLists(); decorate(); })));
    const step = preview && valid && preview.steps[selectedStep];
    $("strand-transport").textContent = step ? `Entry IDs: ${step.entry.join(" ")}\nExit IDs: ${step.exit.join(" ")}` :
      recipe.braid.word.length ? "Select a valid crossing to inspect transported strand identities." : "Empty word: straight identity strands.";
    for (const id of ["crossing-up", "crossing-down", "invert-crossing", "delete-crossing"])
      $(id).disabled = !recipe.braid.word.length;
    $("crossing-up").disabled ||= selectedStep === 0;
    $("crossing-down").disabled ||= selectedStep === recipe.braid.word.length-1;
  }
  $("label-list").replaceChildren(...recipe.labels.map(l => itemButton(l.text || l.id, l.id === selectedLabel,
    () => { selectedLabel = l.id; syncLists(); decorate(); }, l.color)));
  const label = recipe.labels.find(l => l.id === selectedLabel);
  $("label-editor").hidden = !label;
  if (label) for (const key of ["text", "x", "y", "size", "color"])
    $("label-"+key).value = key === "color" ? color6(label[key]) : label[key];
}
function color6(value) { return value.length === 4 ? "#"+[...value.slice(1)].map(c => c+c).join("") : value; }
function syncObjects() {
  $("objects").replaceChildren(...recipe.surface.objects.map((object, index) => {
    const row = document.createElement("div"); row.className = "object-row";
    const name = document.createElement("span"); name.textContent = index+1; name.title = object.id; row.append(name);
    const kind = document.createElement("select"); kind.setAttribute("aria-label", `Object ${index+1} kind`);
    for (const [value, text] of [["point", "Point"], ["boundary", "Boundary"]]) {
      const option = document.createElement("option"); option.value = value; option.textContent = text; kind.append(option);
    }
    kind.value = object.kind; kind.onchange = () => { const next = clone(recipe); next.surface.objects[index].kind = kind.value; commit(next); }; row.append(kind);
    for (const key of ["x", "radius"]) {
      const input = document.createElement("input"); input.type = "number"; input.value = object[key] ?? "";
      input.placeholder = "Auto"; input.setAttribute("aria-label", `Object ${index+1} ${key}`);
      input.onchange = () => {
        if (!(key === "radius" && input.value === "") && (!input.value.trim() || !Number.isFinite(Number(input.value)))) {
          inputError("Enter a finite object position or radius."); return;
        }
        const next = clone(recipe); next.surface.objects[index][key] = key === "radius" && input.value === "" ? null : Number(input.value); commit(next);
      };
      row.append(input);
    }
    return row;
  }));
}
function sync() {
  const planar = recipe.kind === "planar";
  $("title").value = recipe.title; document.title = recipe.title+" · Surface diagrams";
  $("planar-settings").hidden = !planar; $("braid-settings").hidden = planar;
  $("new-planar").setAttribute("aria-pressed", planar); $("new-braid").setAttribute("aria-pressed", !planar);
  document.querySelectorAll('[data-tool="arc"], [data-tool="loop"]').forEach(e => e.hidden = !planar);
  $("undo").disabled = !undo.length; $("redo").disabled = !redo.length;
  $("curve-width").value = recipe.style.curve_width; $("point-radius").value = recipe.style.marked_point_radius;
  $("outline").checked = recipe.style.show_outer_ellipse;
  if (planar) {
    $("width").value = recipe.surface.width; $("height").value = recipe.surface.height;
    $("pattern").value = recipe.surface.objects.map(o => o.kind === "point" ? "P" : "B").join("");
    $("boundary-shape").value = recipe.style.boundary_shape; $("guides").checked = recipe.style.show_guides;
    $("intersections").checked = recipe.allow_intersections; $("overlay-warning").hidden = !recipe.allow_intersections;
    syncObjects();
  } else {
    $("strands").value = recipe.braid.strands; $("word").value = recipe.braid.word.join(", ");
    $("braid-direction").value = recipe.braid.direction; $("braid-spacing").value = recipe.braid.spacing; $("braid-step").value = recipe.braid.step;
    $("braid-crossing-style").value = recipe.braid.crossing_style || "straight";
  }
  syncLists(); saveStateLabel(); $("recipe").textContent = JSON.stringify(recipe, null, 2);
}
function setTool(value) {
  tool = value; start = null; visits = [];
  document.querySelectorAll("[data-tool]").forEach(e => e.setAttribute("aria-pressed", e.dataset.tool === tool));
  $("finish-loop").hidden = tool !== "loop"; $("cancel-tool").hidden = tool === "select";
  instruction(); decorate();
}
function instruction() {
  $("instruction").textContent = tool === "arc" ? (start === null ? "Click a numbered endpoint to start an arc." :
    `Start ${start}. Click cut intervals in order, then the end endpoint. Visits: ${visits.join(", ") || "none"}.`) :
    tool === "loop" ? `Click cut intervals in order, then Finish loop. Visits: ${visits.join(", ") || "none"}.` :
    tool === "label" ? "Click the drawing to place a label, then edit its text in the sidebar." :
    recipe?.kind === "braid" ? "Select a crossing to inspect its entry and exit strand identities." :
    "Select a curve to edit it. Drag a point along the axis; drag a label freely.";
}
function addCurve(end) {
  if (recipe.curves.length >= 16) { showError("This editor supports at most 16 curves."); return; }
  const next = clone(recipe), id = unique(tool, next.curves);
  const curve = {id, kind: tool, cuts: [...visits], color: recipe.style.curve_color};
  if (tool === "arc") Object.assign(curve, {start, end, direction: "default", start_side: null, end_side: null});
  else curve.start_up = true;
  next.curves.push(curve); selectedCurve = id;
  setTool("select"); commit(next);
}
function localPoint(event, svg) {
  const point = new DOMPoint(event.clientX, event.clientY).matrixTransform(svg.getScreenCTM().inverse());
  return {x: point.x-preview.width/2, y: preview.height/2-point.y};
}
function decorate() {
  const svg = $("drawing").querySelector("svg"); if (!svg || !valid) return;
  svg.querySelector(".editing-handles")?.remove();
  svg.classList.toggle("pick-mode", tool === "arc" || tool === "loop");
  const layer = svgElement("g", {class: "editing-handles"}); svg.append(layer);
  if (recipe.kind === "planar") {
    svg.querySelectorAll("path.arc, path.closed-curve").forEach((path, i) => {
      const curve = recipe.curves[i]; if (!curve) return;
      path.classList.toggle("selected-curve", curve.id === selectedCurve);
      path.onclick = event => { if (tool === "select") { event.stopPropagation(); selectedCurve = curve.id; selectedLabel = null; syncLists(); decorate(); } };
      path.style.cursor = "pointer";
    });
    for (const handle of preview.handles.filter(h => h.kind === "endpoint")) {
      const circle = svgElement("circle", {cx: handle.x, cy: handle.y, r: 12, class: "endpoint-handle", "data-endpoint": handle.number});
      const title = svgElement("title", {}); title.textContent = `Endpoint ${handle.number} (${handle.id})`; circle.append(title); layer.append(circle);
      if (tool === "arc" || tool === "loop") {
        const numberLabel = svgElement("text", {x: handle.x, y: handle.y-17, "text-anchor": "middle", "font-size": 11, fill: "#167464", "pointer-events": "none"});
        numberLabel.textContent = handle.number; layer.append(numberLabel);
      }
      circle.onclick = event => {
        event.stopPropagation();
        if (tool === "arc") { if (start === null) start = handle.number; else addCurve(handle.number); instruction(); }
      };
      circle.onpointerdown = event => {
        if (tool !== "select" || handle.number === 0 || handle.number === recipe.surface.objects.length+1) return;
        beginDrag(event, svg, circle, {kind: "object", index: handle.number-1});
      };
    }
    if (tool === "arc" || tool === "loop") for (const cut of preview.cuts) {
      const group = svgElement("g", {class: "cut-handle", "data-cut": cut.number});
      group.append(svgElement("circle", {cx: cut.x, cy: cut.y+25, r: 11}));
      const text = svgElement("text", {x: cut.x, y: cut.y+29}); text.textContent = cut.number; group.append(text); layer.append(group);
      group.onclick = event => { event.stopPropagation(); visits.push(cut.number); instruction(); };
    }
  } else {
    svg.querySelectorAll("path.braid-strand").forEach((path, i) => {
      path.classList.toggle("selected-curve", Math.floor(i/recipe.braid.strands) === selectedStep && recipe.braid.word.length > 0);
      path.style.cursor = "pointer";
      path.onclick = event => { if (tool !== "label") { event.stopPropagation(); selectedStep = Math.floor(i/recipe.braid.strands); syncLists(); decorate(); } };
    });
  }
  for (const handle of preview.handles.filter(h => h.kind === "label")) {
    const label = recipe.labels.find(l => l.id === handle.id);
    const width = Math.max(18, label.text.length*label.size*.6);
    const rect = svgElement("rect", {x: handle.x-width/2, y: handle.y-label.size, width, height: label.size+5, class: "label-handle"});
    layer.append(rect);
    rect.onpointerdown = event => { if (tool === "select") { selectedLabel = handle.id; syncLists(); beginDrag(event, svg, rect, {kind: "label", id: handle.id}); } };
  }
  svg.onclick = event => {
    if (tool !== "label") return;
    if (recipe.labels.length >= 32) { showError("At most 32 labels are supported."); return; }
    const point = localPoint(event, svg), next = clone(recipe), id = unique("label", next.labels);
    next.labels.push({id, text: "New label", x: Math.round(point.x), y: Math.round(point.y), color: "#000000", size: 12});
    selectedLabel = id; setTool("select"); commit(next);
  };
}
function beginDrag(event, svg, element, target) {
  event.preventDefault(); event.stopPropagation();
  const original = clone(recipe), point = localPoint(event, svg);
  drag = {original, point, target, moved: false};
  svg.setPointerCapture(event.pointerId);
  svg.onpointermove = move => {
    if (!drag) return;
    const at = localPoint(move, svg), next = clone(original);
    if (target.kind === "object") {
      const items = next.surface.objects, i = target.index;
      const low = i ? items[i-1].x+5 : -next.surface.width/2+12;
      const high = i+1 < items.length ? items[i+1].x-5 : next.surface.width/2-12;
      items[i].x = Math.round(Math.max(low, Math.min(high, original.surface.objects[i].x+at.x-point.x)));
      element.setAttribute("cx", items[i].x+preview.width/2);
    } else {
      const label = next.labels.find(l => l.id === target.id), old = original.labels.find(l => l.id === target.id);
      label.x = Math.round(old.x+at.x-point.x); label.y = Math.round(old.y+at.y-point.y);
      element.setAttribute("transform", `translate(${label.x-old.x} ${old.y-label.y})`);
    }
    drag.next = next; drag.moved = true;
  };
  function finish(cancel) {
    if (!drag) return;
    const pending = drag; drag = null;
    svg.onpointermove = svg.onpointerup = svg.onpointercancel = null;
    if (!cancel && pending.moved) commit(pending.next); else decorate();
  }
  svg.onpointerup = () => finish(false); svg.onpointercancel = () => finish(true);
}
function applyZoom() {
  const svg = $("drawing").querySelector("svg"); if (!svg || !preview) return;
  svg.setAttribute("width", preview.width*zoom); svg.setAttribute("height", preview.height*zoom);
  $("zoom").textContent = Math.round(zoom*100)+"%";
}
function fit() {
  if (!preview) return;
  zoom = Math.min(1.5, Math.max(.1, Math.min(($("viewport").clientWidth-95)/preview.width,
    ($("viewport").clientHeight-95)/preview.height)));
  applyZoom();
}
function download(content, filename, type) {
  const url = URL.createObjectURL(new Blob([content], {type}));
  const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click();
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}
function filename(extension) { return (recipe.title.replace(/[^a-zA-Z0-9_-]+/g, "-").replace(/^-|-$/g, "") || "diagram")+extension; }

$("undo").onclick = () => history(true); $("redo").onclick = () => history(false);
$("open").onclick = () => $("file").click();
$("file").onchange = async () => {
  const file = $("file").files[0]; $("file").value = ""; if (!file) return;
  if (dirty() && !confirm("Replace the current draft? Save its JSON first if you need to keep it.")) return;
  try {
    if (file.size > 256*1024) throw new Error("The document exceeds 256 KiB.");
    const next = await (await api("/api/validate", await file.text(), true)).json();
    commit(next); saved = JSON.stringify(next); setTool("select"); saveStateLabel();
  } catch (error) { $("error").textContent = "File not opened: "+error.message; $("error").hidden = false; }
};
$("save").onclick = () => { download(JSON.stringify(recipe, null, 2)+"\n", filename(".json"), "application/json"); saved = JSON.stringify(recipe); saveStateLabel(); };
$("export").onclick = async () => {
  if (!valid) return;
  const current = revision, kind = $("export-kind").value;
  try {
    const content = await (await api("/api/export/"+kind, recipe)).text();
    if (current !== revision) return;
    download(content, filename(kind === "python" ? ".py" : "."+kind), kind === "svg" ? "image/svg+xml" : "text/plain");
  } catch (error) { if (current === revision) showError(error.message); }
};
for (const kind of ["planar", "braid"]) $("new-"+kind).onclick = () => {
  if (dirty() && !confirm("Start a new "+kind+" document? The current draft stays available with Undo.")) return;
  commit(clone(examples[kind])); selectedCurve = null; selectedLabel = null; selectedStep = 0; setTool("select"); syncLists();
};
document.querySelectorAll("[data-tool]").forEach(button => button.onclick = () => setTool(button.dataset.tool));
$("finish-loop").onclick = () => addCurve(); $("cancel-tool").onclick = () => setTool("select");
$("zoom-in").onclick = () => { zoom = Math.min(4, zoom*1.2); applyZoom(); };
$("zoom-out").onclick = () => { zoom = Math.max(.1, zoom/1.2); applyZoom(); }; $("fit").onclick = fit;
change("title", next => next.title = $("title").value);
for (const key of ["width", "height"]) change(key, next => next.surface[key] = number(key));
change("spacing", next => { const space = number("spacing"), n = next.surface.objects.length;
  next.surface.objects.forEach((o, i) => o.x = (i-(n-1)/2)*space);
  next.surface.width = Math.max(next.surface.width, (n-1)*space+100);
});
$("rebuild-row").onclick = () => {
  try {
    const pattern = $("pattern").value.toUpperCase().replace(/\s/g, "");
    if (!/^[PB]{0,32}$/.test(pattern)) throw new Error("Use at most 32 P/B objects.");
    if (recipe.curves.length && !confirm("Rebuilding the row changes endpoint numbering and will clear all curves. Continue?")) return;
    const space = number("spacing"), next = clone(recipe);
    next.surface.objects = [...pattern].map((kind, i) => ({id: "object"+(i+1), kind: kind === "P" ? "point" : "boundary", x: (i-(pattern.length-1)/2)*space, y: 0, radius: null}));
    next.surface.width = Math.max(next.surface.width, (pattern.length-1)*space+100); next.curves = []; selectedCurve = null; commit(next);
  } catch (error) { showError(error.message); }
};
change("boundary-shape", next => { next.style.boundary_shape = $("boundary-shape").value; next.style.boundary_radius = next.style.boundary_shape === "circle" ? 12 : 4; });
change("guides", next => next.style.show_guides = $("guides").checked);
change("intersections", next => next.allow_intersections = $("intersections").checked);
for (const [id, field, type] of [["curve-id", "id", "text"], ["curve-color", "color", "text"], ["curve-cuts", "cuts", "cuts"],
  ["curve-start", "start", "number"], ["curve-end", "end", "number"], ["curve-direction", "direction", "text"],
  ["start-side", "start_side", "side"], ["end-side", "end_side", "side"], ["loop-up", "start_up", "boolean"]]) {
  change(id, next => {
    const curve = next.curves.find(c => c.id === selectedCurve); if (!curve) return;
    curve[field] = type === "number" ? number(id) : type === "cuts" ? integers($(id).value) : type === "boolean" ? $(id).checked : type === "side" ? $(id).value || null : $(id).value;
    if (field === "id") selectedCurve = curve.id;
  });
}
$("delete-curve").onclick = () => { const next = clone(recipe); next.curves = next.curves.filter(c => c.id !== selectedCurve); selectedCurve = null; commit(next); };
for (const [id, key] of [["strands", "strands"], ["braid-spacing", "spacing"], ["braid-step", "step"]]) change(id, next => next.braid[key] = number(id));
change("word", next => next.braid.word = integers($("word").value)); change("braid-direction", next => next.braid.direction = $("braid-direction").value);
change("braid-crossing-style", next => next.braid.crossing_style = $("braid-crossing-style").value);
$("append-generator").onclick = () => { try { const next = clone(recipe); next.braid.word.push(number("generator")); selectedStep = next.braid.word.length-1; commit(next); } catch (error) { showError(error.message); } };
$("invert-crossing").onclick = () => { const next = clone(recipe); next.braid.word[selectedStep] *= -1; commit(next); };
$("delete-crossing").onclick = () => { const next = clone(recipe); next.braid.word.splice(selectedStep, 1); commit(next); };
for (const [id, offset] of [["crossing-up", -1], ["crossing-down", 1]]) $(id).onclick = () => {
  const next = clone(recipe), other = selectedStep+offset;
  if (other < 0 || other >= next.braid.word.length) return;
  [next.braid.word[selectedStep], next.braid.word[other]] = [next.braid.word[other], next.braid.word[selectedStep]];
  selectedStep = other; commit(next);
};
for (const key of ["text", "x", "y", "size", "color"]) change("label-"+key, next => {
  const label = next.labels.find(l => l.id === selectedLabel); if (label) label[key] = ["x", "y", "size"].includes(key) ? number("label-"+key) : $("label-"+key).value;
});
$("delete-label").onclick = () => { const next = clone(recipe); next.labels = next.labels.filter(l => l.id !== selectedLabel); selectedLabel = null; commit(next); };
change("curve-width", next => next.style.curve_width = number("curve-width"));
change("point-radius", next => next.style.marked_point_radius = number("point-radius"));
change("outline", next => next.style.show_outer_ellipse = $("outline").checked);
window.addEventListener("beforeunload", event => { if (dirty()) { event.preventDefault(); event.returnValue = ""; } });
document.addEventListener("keydown", event => {
  if (event.key === "Escape") setTool("select");
  if (!(event.ctrlKey || event.metaKey) || /INPUT|TEXTAREA|SELECT/.test(event.target.tagName)) return;
  if (event.key.toLowerCase() === "z") { event.preventDefault(); history(!event.shiftKey); }
  if (event.key.toLowerCase() === "s") { event.preventDefault(); $("save").click(); }
});
(async () => {
  try {
    const response = await fetch("/api/session"); if (!response.ok) throw new Error("Could not connect to the local editor");
    const session = await response.json(); token = session.token; examples = session.examples;
    recipe = clone(examples.planar); saved = JSON.stringify(recipe); sync(); await render(); fit();
  } catch (error) { showError(error.message); }
})();
